[project]
name = "esmote"
version = "0.1.0"
requires-python = ">=3.7"
description = "AALTD imblanced classification ESMOTE:Generating synthetic samples in imbalanced datasets"
dependencies = [
    "aeon",
]
