[project]
name = "esmote"
version = "0.1.0"
requires-python = ">=3.7"
description = "A Python package for generating synthetic samples in imbalanced datasets using the ESMOTE algorithm."
dependencies = [
    "aeon",
]
